using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Yachasoft.Sri.Core.Atributos;

namespace Yachasoft.Sri.Modelos.Enumerados
{
    public enum EnumTipoImpuestoICE
    {
        [SRICodigo("3011", TarifaEspecificaEnDic2020 = "0.1600"), Display(Name = "ICE Cigarillos Rubios")] CigarillosRubios,
        [SRICodigo("3021", TarifaEspecificaEnDic2020 = "0.1600"), Display(Name = "ICE Cigarillos Negros")] CigarrillosNegros,
        [SRICodigo("3023", Porcentaje = 150.0), Display(Name = "ICE Productos del Tabaco y Sucedáneos del Tabaco excepto Cigarrillos")] ProductosTabacoySucedaneosExceptoCigarillos,
        [SRICodigo("3031", Porcentaje = 75.0), Display(Name = "ICE Bebidas Alcohólicas")] BebidasAlcoholicas,
        [SRICodigo("3041", Porcentaje = 75.0, TarifaEspecificaEnDic2020 = "13.2000"), Display(Name = "ICE Cerveza Industrial Gran Escala")] CervezaIndustrialGranEscala,
        [SRICodigo("3041", Porcentaje = 75.0, TarifaEspecificaEnDic2020 = "10.5800"), Display(Name = "ICE Cerveza Industrial Mediana Escala")] CervezaIndustrialMedianaEscala,
        [SRICodigo("3041", Porcentaje = 75.0, TarifaEspecificaEnDic2020 = "8.4900"), Display(Name = "ICE Cerveza Industrial Pequeña Escala")] CervezaIndustrialPequenaEscala,
        [SRICodigo("3073", Porcentaje = 5.0), Display(Name = "ICE Vehículos Motorizados cuyo PVP sea hasta de 20000 USD")] VehículosMotorizadoscuyoPVPseahastade20000USD,
        [SRICodigo("3075", Porcentaje = 15.0), Display(Name = "ICE Vehículos Motorizados PVP entre 30000 y 40000")] VehículosMotorizadosPVPentre30000y40000,
        [SRICodigo("3077", Porcentaje = 20.0), Display(Name = "ICE Vehículos Motorizados cuyo PVP superior USD 40.000 hasta 50.000")] VehículosMotorizadoscuyoPVPsuperiorUSD40000hasta50000,
        [SRICodigo("3078", Porcentaje = 25.0), Display(Name = "ICE Vehículos Motorizados cuyo PVP superior USD 50.000 hasta 60.000")] VehículosMotorizadoscuyoPVPsuperiorUSD50000hasta60000,
        [SRICodigo("3079", Porcentaje = 30.0), Display(Name = "ICE Vehículos Motorizados cuyo PVP superior USD 60.000 hasta 70.000")] VehículosMotorizadoscuyoPVPsuperiorUSD60000hasta70000,
        [SRICodigo("3080", Porcentaje = 35.0), Display(Name = "ICE Vehículos Motorizados cuyo PVP superior USD 70.000")] VehículosMotorizadoscuyoPVPsuperiorUSD70000,
        [SRICodigo("3081", Porcentaje = 15.0), Display(Name = "ICE Aviones, Tricares, yates, Barcos de Recreo")] AvionesTricaresyatesBarcosdeRecreo,
        [SRICodigo("3092", Porcentaje = 15.0), Display(Name = "ICE Servicios de Televisión Prepagada")] ServiciosdeTelevisiónPrepagada,
        [SRICodigo("3610", Porcentaje = 20.0), Display(Name = "ICE Perfumes y Aguas de Tocador")] PerfumesyAguasdeTocador,
        [SRICodigo("3620", Porcentaje = 35.0), Display(Name = "ICE Videojuegos")] Videojuegos,
        [SRICodigo("3630", Porcentaje = 300.0), Display(Name = "ICE Armas de Fuego, Armas deportivas y Municiones")] ArmasdeFuegoArmasdeportivasyMuniciones,
        [SRICodigo("3640", Porcentaje = 100.0), Display(Name = "ICE Focos Incandescentes")] FocosIncandescentes,
        [SRICodigo("3660", Porcentaje = 35.0), Display(Name = "ICE Cuotas Membresías Afiliaciones Acciones")] CuotasMembresíasAfiliacionesAcciones,
        [SRICodigo("3093", Porcentaje = 15.0), Display(Name = "ICE Servicios Telefonía Sociedades")] ServiciosTelefoníaSociedades,
        [SRICodigo("3101", Porcentaje = 10.0), Display(Name = "ICE Bebidas Energizantes")] BebidasEnergizantes,
        [SRICodigo("3053", TarifaEspecificaEnDic2020 = "0,18 por 100 gramos de azúcar"), Display(Name = "ICE Bebidas Gaseosas con Alto Contenido de Azúcar")] BebidasGaseosasconAltoContenidodeAzúcar,
        [SRICodigo("3054", Porcentaje = 10.0), Display(Name = "ICE Bebidas Gaseosas con Bajo Contenido de Azúcar")] BebidasGaseosasconBajoContenidodeAzúcar,
        [SRICodigo("3111", TarifaEspecificaEnDic2020 = "0,18 por 100 gramos de azúcar"), Display(Name = "ICE Bebidas No Alcohólicas")] BebidasNoAlcohólicas,
        [SRICodigo("3043", TarifaEspecificaEnDic2020 = "1,1500"), Display(Name = "ICE Cerveza Artesanal")] CervezaArtesanal,
        [SRICodigo("3033", Porcentaje = 75.0, TarifaEspecificaEnDic2020 = "7,22"), Display(Name = "ICE Alcohol")] Alcohol,
        [SRICodigo("3671", Porcentaje = 100.0), Display(Name = "ICE CALEFONES Y SISTEMAS DE CALENTAMIENTO DE AGUA A GAS SRI")] CALEFONESYSISTEMASDECALENTAMIENTODEAGUAAGASSRI,
        [SRICodigo("3684", Porcentaje = 5.0), Display(Name = "ICE VEHÍCULOS MOTORIZADOS CAMIONETAS Y DE RESCATE CUYO PVP SEA HASTA DE 30.000 USD")] VEHÍCULOSMOTORIZADOSCAMIONETASYDERESCATECUYOPVPSEAHASTADE30000USD,
        [SRICodigo("3686", Porcentaje = 10.0), Display(Name = "ICE VEHÍCULOS MOTORIZADOS EXCEPTO CAMIONETAS Y DE RESCATE CUYO PVP SEA SUPERIOR USD 20.000 HASTA DE 30.000")] VEHÍCULOSMOTORIZADOSEXCEPTOCAMIONETASYDERESCATECUYOPVPSEASUPERIORUSD20000HASTADE30000,
        [SRICodigo("3688", Porcentaje = 0.0), Display(Name = "ICE VEHÍCULOS HÍBRIDOS CUYO PVP SEA DE HASTA USD. 35.000")] VEHÍCULOSHÍBRIDOSCUYOPVPSEADEHASTAUSD35000,
        [SRICodigo("3691", Porcentaje = 8.0), Display(Name = "ICE VEHÍCULOS HÍBRIDOS CUYO PVP SUPERIOR USD. 35.000 HASTA 40.000")] VEHÍCULOSHÍBRIDOSCUYOPVPSUPERIORUSD35000HASTA40000,
        [SRICodigo("3692", Porcentaje = 14.0), Display(Name = "ICE VEHÍCULOS HÍBRIDOS CUYO PVP SUPERIOR USD. 40.000 HASTA 50.000")] VEHÍCULOSHÍBRIDOSCUYOPVPSUPERIORUSD40000HASTA50000,
        [SRICodigo("3695", Porcentaje = 20.0), Display(Name = "ICE VEHÍCULOS HÍBRIDOS CUYO PVP SUPERIOR USD. 50.000 HASTA 60.000")] VEHÍCULOSHÍBRIDOSCUYOPVPSUPERIORUSD50000HASTA60000,
        [SRICodigo("3696", Porcentaje = 26.0), Display(Name = "ICE VEHÍCULOS HÍBRIDOS CUYO PVP SUPERIOR USD. 60.000 HASTA 70.000")] VEHÍCULOSHÍBRIDOSCUYOPVPSUPERIORUSD60000HASTA70000,
        [SRICodigo("3698", Porcentaje = 32.0), Display(Name = "ICE VEHÍCULOS HÍBRIDOS CUYO PVP SUPERIOR A USD 70.000")] VEHÍCULOSHÍBRIDOSCUYOPVPSUPERIORAUSD70000,
        [SRICodigo("3682", Porcentaje = 150.0), Display(Name = "ICE CONSUMIBLES TABACO CALENTADO Y LIQUIDOS CON NICOTINA SRI")] CONSUMIBLESTABACOCALENTADOYLIQUIDOSCONNICOTINASRI,
        [SRICodigo("3681", Porcentaje = 10.0), Display(Name = "ICE SERVICIOS DE TELEFONÍA MÓVIL PERSONAS NATURALES")] SERVICIOSDETELEFONÍAMÓVILPERSONASNATURALES,
        [SRICodigo("3680", TarifaEspecifica9MayADic2020 = "0,04"), Display(Name = "ICE FUNDAS PLÁSTICAS")] FUNDASPLÁSTICAS,
        [SRICodigo("3533", Porcentaje = 75.0, TarifaEspecificaEnDic2020 = "7,2500"), Display(Name = "ICE Import.Bebidas Alcohólicas")] ImportBebidasAlcohólicas,
        [SRICodigo("3541", Porcentaje = 75.0, TarifaEspecificaEnDic2020 = "7,2500"), Display(Name = "ICE Cerveza Gran Escala Cae")] CervezaGranEscalaCae,
        [SRICodigo("3541", Porcentaje = 75.0, TarifaEspecificaEnDic2020 = "13,2000"), Display(Name = "ICE Cerveza Industrial de Mediana Escala Cae")] CervezaIndustrialdeMedianaEscalaCae,
        [SRICodigo("3541", Porcentaje = 75.0, TarifaEspecificaEnDic2020 = "10,5800"), Display(Name = "ICE Cerveza Industrial de Pequeña Escala Cae")] CervezaIndustrialdePequeñaEscalaCae,
        [SRICodigo("3542", TarifaEspecificaEnDic2020 = "0,1600"), Display(Name = "ICE Cigarrillos Rubios Cae")] CigarrillosRubiosCae,
        [SRICodigo("3543", TarifaEspecificaEnDic2020 = "0,1600"), Display(Name = "ICE Cigarrillos Negros Cae")] CigarrillosNegrosCae,
        [SRICodigo("3544", Porcentaje = 150.0), Display(Name = "ICE Productos del Tabaco y Sucedaneos del Tabaco Excepto Cigarrillos Cae")] ProductosdelTabacoySucedaneosdelTabacoExceptoCigarrillosCae,
        [SRICodigo("3581", Porcentaje = 15.0), Display(Name = "ICE Aeronaves Cae")] AeronavesCae,
        [SRICodigo("3582", Porcentaje = 15.0), Display(Name = "ICE Aviones, Avionetas y Helicopteros Exct.Aquellos destinados Al Trans.Cae")] AvionesAvionetasyHelicopterosExctAquellosdestinadosAlTransCae,
        [SRICodigo("3710", Porcentaje = 20.0), Display(Name = "ICE Perfumes Aguas de Tocador Cae")] PerfumesAguasdeTocadorCae,
        [SRICodigo("3720", Porcentaje = 35.0), Display(Name = "ICE Video Juegos Cae")] VideoJuegosCae,
        [SRICodigo("3730", Porcentaje = 300.0), Display(Name = "ICE Importaciones Armas de Fuego, Armas deportivas y Municiones Cae")] ImportacionesArmasdeFuegoArmasdeportivasyMunicionesCae,
        [SRICodigo("3740", Porcentaje = 100.0), Display(Name = "ICE Focos Incandecentes Cae")] FocosIncandecentesCae,
        [SRICodigo("3871", Porcentaje = 5.0), Display(Name = "ICE VEHÍCULOS MOTORIZADOS CUYO PVP SEA HASTA DE 20000 USD SENAE")] VEHÍCULOSMOTORIZADOSCUYOPVPSEAHASTADE20000USDSENAE,
        [SRICodigo("3873", Porcentaje = 15.0), Display(Name = "ICE VEHÍCULOS MOTORIZADOS PVP ENTRE 30000 Y 40000 SENAE")] VEHÍCULOSMOTORIZADOSPVPENTRE30000Y40000SENAE,
        [SRICodigo("3874", Porcentaje = 20.0), Display(Name = "ICE VEHÍCULOS MOTORIZADOS CUYO PVP SUPERIOR USD 40.000 HASTA 50.000 SENAE")] VEHÍCULOSMOTORIZADOSCUYOPVPSUPERIORUSD40000HASTA50000SENAE,
        [SRICodigo("3875", Porcentaje = 25.0), Display(Name = "ICE VEHÍCULOS MOTORIZADOS CUYO PVP SUPERIOR USD 50.000 HASTA 60.000 SENAE")] VEHÍCULOSMOTORIZADOSCUYOPVPSUPERIORUSD50000HASTA60000SENAE,
        [SRICodigo("3876", Porcentaje = 30.0), Display(Name = "ICE VEHÍCULOS MOTORIZADOS CUYO PVP SUPERIOR USD 60.000 HASTA 70.000 SENAE")] VEHÍCULOSMOTORIZADOSCUYOPVPSUPERIORUSD60000HASTA70000SENAE,
        [SRICodigo("3877", Porcentaje = 35.0), Display(Name = "ICE VEHÍCULOS MOTORIZADOS CUYO PVP SUPERIOR USD 70.000 SENAE")] VEHÍCULOSMOTORIZADOSCUYOPVPSUPERIORUSD70000SENAE,
        [SRICodigo("3878", Porcentaje = 15.0), Display(Name = "ICE Aviones, Tricares, Yates, Barcos De Rec SENAE")] AvionesTricaresYatesBarcosDeRecSENAE,
        [SRICodigo("3601", Porcentaje = 10.0), Display(Name = "ICE Bebidas Energizantes SENAE")] BebidasEnergizantesSENAE,
        [SRICodigo("3552", TarifaEspecificaEnDic2020 = "0,18 por 100 gramos de azúcar"), Display(Name = "ICE BEBIDAS GASEOSAS CON ALTO CONTENIDO DE AZUCAR SENAE")] BEBIDASGASEOSASCONALTOCONTENIDODEAZUCARSENAE,
        [SRICodigo("3553", Porcentaje = 10.0), Display(Name = "ICE BEBIDAS GASEOSAS CON BAJO CONTENIDO DE AZÚCAR SENAE")] BEBIDASGASEOSASCONBAJOCONTENIDODEAZÚCARSENAE,
        [SRICodigo("3602", TarifaEspecificaEnDic2020 = "0,18 por 100 gramos de azúcar"), Display(Name = "ICE BEBIDAS NO ALCOHOLICAS SENAE")] BEBIDASNOALCOHOLICASSENAE,
        [SRICodigo("3545", Porcentaje = 75.0, TarifaEspecificaEnDic2020 = "1,5000"), Display(Name = "ICE CERVEZA ARTESANAL SENAE")] CERVEZAARTESANALSENAE,
        [SRICodigo("3532", Porcentaje = 75.0, TarifaEspecificaEnDic2020 = "7,2200"), Display(Name = "ICE IMPORT.ALCOHOL SENAE")] IMPORTALCOHOLSENAE,
        [SRICodigo("3771", Porcentaje = 100.0), Display(Name = "ICE CALEFONES Y SISTEMAS DE CALENTAMIENTO DE AGUA A GAS SENAE")] CALEFONESYSISTEMASDECALENTAMIENTODEAGUAAGASSENAE,
        [SRICodigo("3685", Porcentaje = 5.0), Display(Name = "ICE VEHÍCULOS MOTORIZADOS CAMIONETAS Y DE RESCATE PVP SEA HASTA DE 30.000 USD SENAE")] VEHÍCULOSMOTORIZADOSCAMIONETASYDERESCATEPVPSEAHASTADE30000USDSENAE,
        [SRICodigo("3687", Porcentaje = 10.0), Display(Name = "ICE VEHÍCULOS MOTORIZADOS EXCEPTO CAMIONETAS Y DE RESCATE CUYO PVP SEA SUPERIOR USD 20.000 HASTA DE 30.000 SENAE")] VEHÍCULOSMOTORIZADOSEXCEPTOCAMIONETASYDERESCATECUYOPVPSEASUPERIORUSD20000HASTADE30000SENAE,
        [SRICodigo("3689", Porcentaje = 0.0), Display(Name = "ICE VEHÍCULOS HÍBRIDOS CUYO PVP SEA DE HASTA USD. 35.000 SENAE")] VEHÍCULOSHÍBRIDOSCUYOPVPSEADEHASTAUSD35000SENAE,
        [SRICodigo("3690", Porcentaje = 8.0), Display(Name = "ICE VEHÍCULOS HÍBRIDOS CUYO PVP SUPERIOR USD. 35.000 HASTA 40.000 SENAE")] VEHÍCULOSHÍBRIDOSCUYOPVPSUPERIORUSD35000HASTA40000SENAE,
        [SRICodigo("3693", Porcentaje = 14.0), Display(Name = "ICE VEHÍCULOS HÍBRIDOS CUYO PVP SUPERIOR USD. 40.000 HASTA 50.000 SENAE")] VEHÍCULOSHÍBRIDOSCUYOPVPSUPERIORUSD40000HASTA50000SENAE,
        [SRICodigo("3694", Porcentaje = 20.0), Display(Name = "ICE VEHÍCULOS HÍBRIDOS CUYO PVP SUPERIOR USD. 50.000 HASTA 60.000 SENAE")] VEHÍCULOSHÍBRIDOSCUYOPVPSUPERIORUSD50000HASTA60000SENAE,
        [SRICodigo("3697", Porcentaje = 26.0), Display(Name = "ICE VEHÍCULOS HÍBRIDOS CUYO PVP SUPERIOR USD. 60.000 HASTA 70.000 SENAE")] VEHÍCULOSHÍBRIDOSCUYOPVPSUPERIORUSD60000HASTA70000SENAE,
        [SRICodigo("3699", Porcentaje = 32.0), Display(Name = "ICE VEHÍCULOS HÍBRIDOS CUYO PVP SUPERIOR A USD 70.000 SENAE")] VEHÍCULOSHÍBRIDOSCUYOPVPSUPERIORAUSD70000SENAE,
        [SRICodigo("3683", Porcentaje = 150.0), Display(Name = "ICE CONSUMIBLES TABACO CALENTADO Y LIQUIDOS CON NICOTINA SENAE")] CONSUMIBLESTABACOCALENTADOYLIQUIDOSCONNICOTINASENAE,
    }
}
